# Generated by Django 3.1.8 on 2021-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='grid',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
