# Generated by Django 3.1.8 on 2021-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='grid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
